replicaCount: 2

image:
  repository: boicotaz/taskapp-frontend
  pullPolicy: Always
  tag: "52e331eb0587dd7d9285cba7fc91d4461e51b65e"

service:
  type: ClusterIP
  port: 80

applicationPort: 80

ingress:
  enabled: true
  path: /
  pathType: Prefix
  className: nginx

backend:
  serviceName: taskapp-backend
  servicePort: 80

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  keda:
    prometheusAddress: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
    nginxRequestsPerSecond:
      enabled: true
      query: 'sum(rate(nginx_http_requests_total{namespace="default", pod=~"taskapp-frontend-.*"}[1m]))'
      threshold: "5"

serviceMonitor:
  enabled: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}