apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "backend-operator.fullname" . }}-manager-role
  labels:
  {{- include "backend-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.taskapp.io
  resources:
  - backends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.taskapp.io
  resources:
  - backends/finalizers
  verbs:
  - update
- apiGroups:
  - apps.taskapp.io
  resources:
  - backends/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - database.taskapp.io
  resources:
  - rdsinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.taskapp.io
  resources:
  - rdsinstances/status
  verbs:
  - get
- apiGroups:
  - db.atlasgo.io
  resources:
  - atlasschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.atlasgo.io
  resources:
  - atlasschemas/status
  verbs:
  - get
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - queue.taskapp.io
  resources:
  - sqsqueues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - queue.taskapp.io
  resources:
  - sqsqueues/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "backend-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "backend-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "backend-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "backend-operator.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
