image:
  repository: boicotaz/taskapp-backend
  tag: "27a621a534ab788d32d5651269c1492b72188f57"

replicas: 2

database:
  enabled: true
  dbName: taskdb
  size: small
  schema:
    sql: |
      CREATE TABLE IF NOT EXISTS tasks (
        id          SERIAL PRIMARY KEY,
        title       VARCHAR(255),
        description TEXT,
        status      VARCHAR(50),
        created_at  TIMESTAMP DEFAULT NOW()
      );

queue:
  enabled: true
  type: standard
  deadLetter: false

sqs:
  region: eu-west-1
  queueUrl: ""

keda:
  enabled: false
  minReplicaCount: 1
  maxReplicaCount: 10
  queueLength: "5"
  cooldownPeriod: 300
