controllerManager:
  manager:
    args:
    - --metrics-bind-address=:8443
    - --leader-elect
    - --health-probe-bind-address=:8081
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    defaultQueueRegion: eu-west-1
    image:
      repository: boicotaz/taskapp-backend-operator
      tag: "13adb0db2e5adeeb002326bcd0376b68ced52ca1"
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 125m
        memory: 64Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ""
