apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-config
  labels:
    app: {{ .Chart.Name }}
data:
  POSTGRES_DB: {{ .Values.db.name | quote }}
  POSTGRES_USER: {{ .Values.db.user | quote }}
