apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.clusterSecretStore.aws.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.clusterSecretStore.aws.credentialsSecret.name }}
            namespace: {{ .Values.clusterSecretStore.aws.credentialsSecret.namespace }}
            key: access-key-id
          secretAccessKeySecretRef:
            name: {{ .Values.clusterSecretStore.aws.credentialsSecret.name }}
            namespace: {{ .Values.clusterSecretStore.aws.credentialsSecret.namespace }}
            key: secret-access-key
