{{- if .Values.crossplane.secretPath }}
{{- range .Values.crossplane.providers }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: {{ .package }}
{{- end }}
{{- end }}
