{{- if .Values.argocdWriteToken.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-write-token
  namespace: default
  labels:
    app: {{ .Chart.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: argocd-write-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: {{ .Values.argocdWriteToken.secretPath }}
      property: token
{{- end }}
