{{- if .Values.awsCredentials.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.awsCredentials.secretName }}
  labels:
    app: {{ .Chart.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.awsCredentials.secretName }}
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: {{ .Values.awsCredentials.secretPath }}
      property: aws_access_key_id
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: {{ .Values.awsCredentials.secretPath }}
      property: aws_secret_access_key
{{- end }}
