{{- if .Values.crossplane.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crossplane-aws-credentials
  namespace: crossplane-system
  labels:
    app: {{ .Chart.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: crossplane-aws-credentials
    creationPolicy: Owner
    template:
      data:
        creds: |
          [default]
          aws_access_key_id = {{ `{{ .aws_access_key_id }}` }}
          aws_secret_access_key = {{ `{{ .aws_secret_access_key }}` }}
  data:
  - secretKey: aws_access_key_id
    remoteRef:
      key: {{ .Values.crossplane.secretPath }}
      property: aws_access_key_id
  - secretKey: aws_secret_access_key
    remoteRef:
      key: {{ .Values.crossplane.secretPath }}
      property: aws_secret_access_key
{{- end }}
