{{- if .Values.crossplaneGithub.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crossplane-github-credentials
  namespace: crossplane-system
  labels:
    app: {{ .Chart.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: crossplane-github-credentials
    creationPolicy: Owner
    template:
      data:
        credentials: |
          {"token":"{{ `{{ .token }}` }}","owner":"{{ `{{ .owner }}` }}"}
  data:
  - secretKey: token
    remoteRef:
      key: {{ .Values.crossplaneGithub.secretPath }}
      property: token
  - secretKey: owner
    remoteRef:
      key: {{ .Values.crossplaneGithub.secretPath }}
      property: owner
{{- end }}
