{{- if .Values.aws.enabled }}
apiVersion: aws.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Values.aws.credentialsSecret.namespace }}
      name: {{ .Values.aws.credentialsSecret.name }}
      key: {{ .Values.aws.credentialsSecret.key }}
{{- end }}
