{{- if .Values.github.enabled }}
apiVersion: github.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Values.github.credentialsSecret.namespace }}
      name: {{ .Values.github.credentialsSecret.name }}
      key: {{ .Values.github.credentialsSecret.key }}
{{- end }}
